name: Publish Nuget

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish_nuget:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: ShipStation.NetSdk/ShipStation.NetSdk.csproj
          PACKAGE_NAME: ShipStation.NetSdk
