name: Push Nuget
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build ShipStation.NetSdk/ShipStation.NetSdk.sln --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test ShipStation.NetSdk/ShipStation.NetSdk.sln --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack ShipStation.NetSdk/ShipStation.NetSdk.sln --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${secrets.NUGET_API_KEY}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
